version: '2'
services:
  cdservice:
    image: ${CD_IMAGE}
    environment:
      VIRTUAL_HOST: service.${DOMAINNAME}
      LETSENCRYPT_HOST: service.${DOMAINNAME}
      LETSENCRYPT_EMAIL: ${EMAIL}

  # Watchtower to upgrade if a new image is pushed to the registry
  watchtower:
    image: v2tec/watchtower:0.1.0
    command: >
      projects_${CD_IMAGE}_1
      --interval 60s
      --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REPO_USER: ${REGISTRY_USER}
      REPO_PASS: ${REGISTRY_PASS}
